### ISSUE TITLE
FE-Halaman Home (USER)

### ISSUE THREAD

**Issue by dimasgda** [ddim03/sipma#1]

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [testing2](https://trello.com/c/UY52ZaRc/26-testing2)

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Halaman Home](https://trello.com/c/pNfafSC0/29-halaman-home)

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Halaman Home](https://trello.com/c/s5ooHeYl/30-halaman-home)

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Halaman Home (USER)](https://trello.com/c/s5ooHeYl/30-halaman-home-user)

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Halaman Home (USER)](https://trello.com/c/s5ooHeYl/30-halaman-home-user)
