### ISSUE TITLE
FE-Halaman Sidebar Pengumuman (Admin)

### ISSUE THREAD

**Issue by dimasgda** [ddim03/sipma#10]

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Halaman Login](https://trello.com/c/sUWM0QFW/27-halaman-login)

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tabel Arsip](https://trello.com/c/FISIaDPQ/35-tabel-arsip)

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Halaman Dashboard (ADMIN)](https://trello.com/c/OBPVCo1K/31-halaman-dashboard-admin)

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Halaman Sidebar Pengumuman (ADMIN)](https://trello.com/c/FISIaDPQ/35-halaman-sidebar-pengumuman-admin)

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Halaman Sidebar Arsip (ADMIN)](https://trello.com/c/K2nhfXvi/42-halaman-sidebar-arsip-admin)

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Halaman Sidebar Pengumuman (ADMIN)](https://trello.com/c/FISIaDPQ/35-halaman-sidebar-pengumuman-admin)
