### ISSUE TITLE
FE-Halaman Pengumuman Berdasarkan Kategori (USER)

### ISSUE THREAD

**Issue by dimasgda** [ddim03/sipma#11]

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Halaman Pengumuman Berdasarkan Kategori](https://trello.com/c/8D8EquRZ/39-halaman-pengumuman-berdasarkan-kategori)

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Halaman Pengumuman Berdasarkan Kategori](https://trello.com/c/8D8EquRZ/39-halaman-pengumuman-berdasarkan-kategori)

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Halaman Detail Pengumuman (USER)](https://trello.com/c/A88dQLTC/34-halaman-detail-pengumuman-user)
