### ISSUE TITLE
BE-Controller Read Data by Category-CLOSED

### ISSUE THREAD

**Issue by dimasgda** [ddim03/sipma#13]

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fungsi lihat data berdasarkan kategori](https://trello.com/c/chH8j4R7/37-fungsi-lihat-data-berdasarkan-kategori)

**Comment by rizkinp** [comment]
CLOSE BECAUSE OF TESTING
