### ISSUE TITLE
BE-Contoller Read Data by Judul

### ISSUE THREAD

**Issue by dimasgda** [ddim03/sipma#14]

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fungsi lihat data berdasarkan judul pengumuman](https://trello.com/c/s1brqBNS/38-fungsi-lihat-data-berdasarkan-judul-pengumuman)

**Comment by rizkinp** [comment]
CLOSE BECAUSE OF TESTING
