### ISSUE TITLE
BE-Model Tabel Pengumuman

### ISSUE THREAD

**Issue by dimasgda** [ddim03/sipma#4]

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Model untuk tabel pengumuman](https://trello.com/c/17LZkeLX/32-model-untuk-tabel-pengumuman)

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Model untuk tabel pengumuman](https://trello.com/c/17LZkeLX/32-model-untuk-tabel-pengumuman)
