### ISSUE TITLE
BE-Controller Read to Pengumuman User

### ISSUE THREAD

**Issue by dimasgda** [ddim03/sipma#5]

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [API untuk menampilkan data ke mahasiswa](https://trello.com/c/umYTt9RR/33-api-untuk-menampilkan-data-ke-mahasiswa)

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [API untuk menampilkan data ke mahasiswa](https://trello.com/c/umYTt9RR/33-api-untuk-menampilkan-data-ke-mahasiswa)
