### ISSUE TITLE
FE-Halaman Detail Pengumuman (Admin)

### ISSUE THREAD

**Issue by dimasgda** [ddim03/sipma#9]

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Halaman Detail Pengumuman](https://trello.com/c/A88dQLTC/34-halaman-detail-pengumuman)

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Halaman Detail Pengumuman (USER)](https://trello.com/c/A88dQLTC/34-halaman-detail-pengumuman-user)

**Comment by rizkinp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Halaman Detail Pengumuman (USER)](https://trello.com/c/A88dQLTC/34-halaman-detail-pengumuman-user)
